# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'read_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEditUser = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditUser.setGeometry(QtCore.QRect(290, 210, 100, 30))
        self.textEditUser.setObjectName("textEditUser")
        self.textEditPassword = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditPassword.setGeometry(QtCore.QRect(290, 260, 100, 30))
        self.textEditPassword.setObjectName("textEditPassword")
        self.labelUser_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelUser_2.setGeometry(QtCore.QRect(210, 270, 50, 15))
        self.labelUser_2.setObjectName("labelUser_2")
        self.labelUser = QtWidgets.QLabel(self.centralwidget)
        self.labelUser.setGeometry(QtCore.QRect(210, 220, 50, 15))
        self.labelUser.setObjectName("labelUser")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(470, 100, 100, 100))
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(470, 250, 100, 100))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.ResultButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResultButton.setGeometry(QtCore.QRect(630, 210, 75, 23))
        self.ResultButton.setObjectName("ResultButton")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.BackButton.setObjectName("BackButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Чтение данных"))
        self.labelUser_2.setText(_translate("MainWindow", "Password"))
        self.labelUser.setText(_translate("MainWindow", "User"))
        self.label_1.setText(_translate("MainWindow", "Перетащи меня"))
        self.label_2.setText(_translate("MainWindow", "Перетащи сюда"))
        self.ResultButton.setText(_translate("MainWindow", "Результат"))
        self.BackButton.setText(_translate("MainWindow", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
