# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'write_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEditUser = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditUser.setGeometry(QtCore.QRect(260, 180, 100, 30))
        self.textEditUser.setObjectName("textEditUser")
        self.textEditPassword = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditPassword.setGeometry(QtCore.QRect(260, 230, 100, 30))
        self.textEditPassword.setObjectName("textEditPassword")
        self.labelUser = QtWidgets.QLabel(self.centralwidget)
        self.labelUser.setGeometry(QtCore.QRect(180, 190, 50, 15))
        self.labelUser.setObjectName("labelUser")
        self.labelUser_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelUser_2.setGeometry(QtCore.QRect(180, 240, 50, 15))
        self.labelUser_2.setObjectName("labelUser_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 290, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ввод данных"))
        self.labelUser.setText(_translate("MainWindow", "User"))
        self.labelUser_2.setText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
