# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choice_room.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChoiceRoomWindow(object):
    def setupUi(self, ChoiceRoomWindow):
        ChoiceRoomWindow.setObjectName("ChoiceRoomWindow")
        ChoiceRoomWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(ChoiceRoomWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(320, 200, 368, 325))
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(5)
        self.scrollArea.setMidLineWidth(5)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 366, 323))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.buttonBack = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBack.setGeometry(QtCore.QRect(320, 541, 140, 27))
        self.buttonBack.setObjectName("buttonBack")
        self.buttonCreateRoom = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCreateRoom.setGeometry(QtCore.QRect(564, 541, 140, 27))
        self.buttonCreateRoom.setObjectName("buttonCreateRoom")
        ChoiceRoomWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChoiceRoomWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        ChoiceRoomWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChoiceRoomWindow)
        self.statusbar.setObjectName("statusbar")
        ChoiceRoomWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChoiceRoomWindow)
        QtCore.QMetaObject.connectSlotsByName(ChoiceRoomWindow)

    def retranslateUi(self, ChoiceRoomWindow):
        _translate = QtCore.QCoreApplication.translate
        ChoiceRoomWindow.setWindowTitle(_translate("ChoiceRoomWindow", "Онлайн игра. Выбор комнаты"))
        self.buttonBack.setText(_translate("ChoiceRoomWindow", "Назад"))
        self.buttonCreateRoom.setText(_translate("ChoiceRoomWindow", "Создать комнату"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChoiceRoomWindow = QtWidgets.QMainWindow()
    ui = Ui_ChoiceRoomWindow()
    ui.setupUi(ChoiceRoomWindow)
    ChoiceRoomWindow.show()
    sys.exit(app.exec_())
