# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'room.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaitingPlayersWindow(object):
    def setupUi(self, WaitingPlayersWindow):
        WaitingPlayersWindow.setObjectName("WaitingPlayersWindow")
        WaitingPlayersWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(WaitingPlayersWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(318, 215, 368, 325))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(5)
        self.frame.setObjectName("frame")
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelInfo.setGeometry(QtCore.QRect(392, 188, 254, 21))
        self.labelInfo.setObjectName("labelInfo")
        self.labelPlayers = QtWidgets.QLabel(self.centralwidget)
        self.labelPlayers.setGeometry(QtCore.QRect(670, 185, 35, 27))
        self.labelPlayers.setObjectName("labelPlayers")
        self.buttonBack = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBack.setGeometry(QtCore.QRect(318, 556, 140, 27))
        self.buttonBack.setObjectName("buttonBack")
        self.buttonStart = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStart.setGeometry(QtCore.QRect(562, 556, 140, 27))
        self.buttonStart.setObjectName("buttonStart")
        WaitingPlayersWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WaitingPlayersWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        WaitingPlayersWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WaitingPlayersWindow)
        self.statusbar.setObjectName("statusbar")
        WaitingPlayersWindow.setStatusBar(self.statusbar)

        self.retranslateUi(WaitingPlayersWindow)
        QtCore.QMetaObject.connectSlotsByName(WaitingPlayersWindow)

    def retranslateUi(self, WaitingPlayersWindow):
        _translate = QtCore.QCoreApplication.translate
        WaitingPlayersWindow.setWindowTitle(_translate("WaitingPlayersWindow", "Онлайн игра. Комната"))
        self.labelInfo.setText(_translate("WaitingPlayersWindow", "Ожидание присоединения других игроков"))
        self.labelPlayers.setText(_translate("WaitingPlayersWindow", "4/7"))
        self.buttonBack.setText(_translate("WaitingPlayersWindow", "Назад"))
        self.buttonStart.setText(_translate("WaitingPlayersWindow", "Начать игру"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaitingPlayersWindow = QtWidgets.QMainWindow()
    ui = Ui_WaitingPlayersWindow()
    ui.setupUi(WaitingPlayersWindow)
    WaitingPlayersWindow.show()
    sys.exit(app.exec_())
