# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QComboBox, QVBoxLayout

import clicked_label

class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(387, 256, 250, 295))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(5)
        self.frame.setObjectName("frame")
        # self.labelBack = QtWidgets.QLabel(self.centralwidget)
        self.labelBack = clicked_label.ClickedLabel(self.centralwidget)
        self.labelBack.setGeometry(QtCore.QRect(410, 272, 48, 48))
        self.labelBack.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBack.setObjectName("labelBack")
        #self.labelMusicOnOff = QtWidgets.QLabel(self.centralwidget)
        self.labelMusicOnOff = clicked_label.ClickedLabel(self.centralwidget)
        self.labelMusicOnOff.setGeometry(QtCore.QRect(494, 272, 48, 48))
        self.labelMusicOnOff.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMusicOnOff.setObjectName("labelMusicOnOff")
        self.labelMusic = QtWidgets.QLabel(self.centralwidget)
        self.labelMusic.setGeometry(QtCore.QRect(400, 350, 100, 48))
        #self.labelMusic.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMusic.setObjectName("labelMusic")
        self.buttonMusicMinus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMusicMinus.setGeometry(QtCore.QRect(503, 360, 33, 27))
        self.buttonMusicMinus.setObjectName("buttonMusicMinus")
        self.buttonMusicPlus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMusicPlus.setGeometry(QtCore.QRect(578, 360, 33, 27))
        self.buttonMusicPlus.setObjectName("buttonMusicPlus")
        self.buttonMusicVolumeMinus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMusicVolumeMinus.setGeometry(QtCore.QRect(503, 427, 33, 27))
        self.buttonMusicVolumeMinus.setObjectName("buttonMusicVolumeMinus")
        self.buttonMusicVolumePlus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMusicVolumePlus.setGeometry(QtCore.QRect(578, 427, 33, 27))
        self.buttonMusicVolumePlus.setObjectName("buttonMusicVolumePlus")
        self.buttonSoundsVolumeMinus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSoundsVolumeMinus.setGeometry(QtCore.QRect(503, 464, 33, 27))
        self.buttonSoundsVolumeMinus.setObjectName("buttonSoundsVolumeMinus")
        self.buttonSoundsVolumePlus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSoundsVolumePlus.setGeometry(QtCore.QRect(578, 464, 33, 27))
        self.buttonSoundsVolumePlus.setObjectName("buttonSoundsVolumePlus")
        self.labelVolume = QtWidgets.QLabel(self.centralwidget)
        self.labelVolume.setGeometry(QtCore.QRect(546, 363, 22, 21))
        self.labelVolume.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVolume.setObjectName("labelVolume")
        self.labelMusicVolume = QtWidgets.QLabel(self.centralwidget)
        self.labelMusicVolume.setGeometry(QtCore.QRect(546, 430, 22, 21))
        self.labelMusicVolume.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMusicVolume.setObjectName("labelMusicVolume")
        self.labelSoundsVolume = QtWidgets.QLabel(self.centralwidget)
        self.labelSoundsVolume.setGeometry(QtCore.QRect(546, 467, 22, 21))
        self.labelSoundsVolume.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSoundsVolume.setObjectName("labelSoundsVolume")
        self.labelMusicVolumeInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelMusicVolumeInfo.setGeometry(QtCore.QRect(400, 430, 100, 21))
        self.labelMusicVolumeInfo.setObjectName("labelMusicVolumeInfo")
        self.labelSoundsVolumeInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelSoundsVolumeInfo.setGeometry(QtCore.QRect(400, 467, 100, 21))
        self.labelSoundsVolumeInfo.setObjectName("labelSoundsVolumeInfo")
        self.labelLanguage = QtWidgets.QLabel(self.centralwidget)
        self.labelLanguage.setGeometry(QtCore.QRect(400, 504, 100, 21))
        self.labelLanguage.setObjectName("labelLanguage")
        SettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        SettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingsWindow)
        self.statusbar.setObjectName("statusbar")
        SettingsWindow.setStatusBar(self.statusbar)

        self.language_button = QComboBox(self.centralwidget)
        self.language_button.addItems(["Русский", "English"])
        self.language_button.setGeometry(QtCore.QRect(503, 500, 108, 27))
        self.language_button.setObjectName("languageButton")

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Настройки"))
        self.labelBack.setText(_translate("SettingsWindow", "<"))
        self.labelMusicOnOff.setText(_translate("SettingsWindow", "bell"))
        self.labelMusic.setText(_translate("SettingsWindow", "Общая громкость"))
        self.buttonMusicMinus.setText(_translate("SettingsWindow", "-"))
        self.buttonMusicPlus.setText(_translate("SettingsWindow", "+"))
        self.buttonMusicVolumeMinus.setText(_translate("SettingsWindow", "-"))
        self.buttonMusicVolumePlus.setText(_translate("SettingsWindow", "+"))
        self.buttonSoundsVolumeMinus.setText(_translate("SettingsWindow", "-"))
        self.buttonSoundsVolumePlus.setText(_translate("SettingsWindow", "+"))
        self.labelVolume.setText(_translate("SettingsWindow", "50"))
        self.labelMusicVolume.setText(_translate("SettingsWindow", "50"))
        self.labelSoundsVolume.setText(_translate("SettingsWindow", "50"))
        self.labelMusicVolumeInfo.setText(_translate("SettingsWindow", "Громкость музыки"))
        self.labelSoundsVolumeInfo.setText(_translate("SettingsWindow", "Громкость звуков"))
        self.labelLanguage.setText(_translate("SettingsWindow", "Язык"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsWindow = QtWidgets.QMainWindow()
    ui = Ui_SettingsWindow()
    ui.setupUi(SettingsWindow)
    SettingsWindow.show()
    sys.exit(app.exec_())
