# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'single2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowSingle2(object):
    def setupUi(self, MainWindowSingle2):
        MainWindowSingle2.setObjectName("MainWindowSingle2")
        MainWindowSingle2.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindowSingle2)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(132, 189, 760, 390))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(5)
        self.frame.setObjectName("frame")
        self.labelBack = QtWidgets.QLabel(self.centralwidget)
        self.labelBack.setGeometry(QtCore.QRect(148, 205, 48, 48))
        self.labelBack.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBack.setObjectName("labelBack")
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelInfo.setGeometry(QtCore.QRect(466, 218, 92, 21))
        self.labelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInfo.setObjectName("labelInfo")
        self.labelRole1 = QtWidgets.QLabel(self.centralwidget)
        self.labelRole1.setGeometry(QtCore.QRect(148, 263, 180, 260))
        self.labelRole1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRole1.setObjectName("labelRole1")
        self.labelRole2 = QtWidgets.QLabel(self.centralwidget)
        self.labelRole2.setGeometry(QtCore.QRect(328, 263, 180, 260))
        self.labelRole2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRole2.setObjectName("labelRole2")
        self.labelRole3 = QtWidgets.QLabel(self.centralwidget)
        self.labelRole3.setGeometry(QtCore.QRect(508, 263, 180, 260))
        self.labelRole3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRole3.setObjectName("labelRole3")
        self.labelRole4 = QtWidgets.QLabel(self.centralwidget)
        self.labelRole4.setGeometry(QtCore.QRect(696, 263, 180, 260))
        self.labelRole4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRole4.setObjectName("labelRole4")
        self.buttonRandomRole = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRandomRole.setGeometry(QtCore.QRect(422, 536, 180, 27))
        self.buttonRandomRole.setObjectName("buttonRandomRole")
        MainWindowSingle2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowSingle2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindowSingle2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowSingle2)
        self.statusbar.setObjectName("statusbar")
        MainWindowSingle2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowSingle2)
        QtCore.QMetaObject.connectSlotsByName(MainWindowSingle2)

    def retranslateUi(self, MainWindowSingle2):
        _translate = QtCore.QCoreApplication.translate
        MainWindowSingle2.setWindowTitle(_translate("MainWindowSingle2", "Одиночная игра. Окно 2"))
        self.labelBack.setText(_translate("MainWindowSingle2", "<"))
        self.labelInfo.setText(_translate("MainWindowSingle2", "Выберите роль"))
        self.labelRole1.setText(_translate("MainWindowSingle2", "Role1"))
        self.labelRole2.setText(_translate("MainWindowSingle2", "Role2"))
        self.labelRole3.setText(_translate("MainWindowSingle2", "Role3"))
        self.labelRole4.setText(_translate("MainWindowSingle2", "Role4"))
        self.buttonRandomRole.setText(_translate("MainWindowSingle2", "Получить случайную роль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowSingle2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindowSingle2()
    ui.setupUi(MainWindowSingle2)
    MainWindowSingle2.show()
    sys.exit(app.exec_())
