# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choice_character.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowChoiceCharacter(object):
    def setupUi(self, MainWindowChoiceCharacter):
        MainWindowChoiceCharacter.setObjectName("MainWindowChoiceCharacter")
        MainWindowChoiceCharacter.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindowChoiceCharacter)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(222, 212, 580, 344))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(5)
        self.frame.setObjectName("frame")
        self.labelBack = QtWidgets.QLabel(self.centralwidget)
        self.labelBack.setGeometry(QtCore.QRect(238, 228, 48, 48))
        self.labelBack.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBack.setObjectName("labelBack")
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelInfo.setGeometry(QtCore.QRect(394, 241, 228, 21))
        self.labelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInfo.setObjectName("labelInfo")
        self.labelCharacter1 = QtWidgets.QLabel(self.centralwidget)
        self.labelCharacter1.setGeometry(QtCore.QRect(238, 286, 180, 260))
        self.labelCharacter1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCharacter1.setObjectName("labelCharacter1")
        self.labelCharacter2 = QtWidgets.QLabel(self.centralwidget)
        self.labelCharacter2.setGeometry(QtCore.QRect(418, 286, 180, 260))
        self.labelCharacter2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCharacter2.setObjectName("labelCharacter2")
        self.labelCharacter3 = QtWidgets.QLabel(self.centralwidget)
        self.labelCharacter3.setGeometry(QtCore.QRect(598, 286, 180, 260))
        self.labelCharacter3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCharacter3.setObjectName("labelCharacter3")
        MainWindowChoiceCharacter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowChoiceCharacter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindowChoiceCharacter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowChoiceCharacter)
        self.statusbar.setObjectName("statusbar")
        MainWindowChoiceCharacter.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowChoiceCharacter)
        QtCore.QMetaObject.connectSlotsByName(MainWindowChoiceCharacter)

    def retranslateUi(self, MainWindowChoiceCharacter):
        _translate = QtCore.QCoreApplication.translate
        MainWindowChoiceCharacter.setWindowTitle(_translate("MainWindowChoiceCharacter", "Выбор персонажа"))
        self.labelBack.setText(_translate("MainWindowChoiceCharacter", "<"))
        self.labelInfo.setText(_translate("MainWindowChoiceCharacter", "Выберите одного из трёх персонажей"))
        self.labelCharacter1.setText(_translate("MainWindowChoiceCharacter", "Character1"))
        self.labelCharacter2.setText(_translate("MainWindowChoiceCharacter", "Character2"))
        self.labelCharacter3.setText(_translate("MainWindowChoiceCharacter", "Character3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowChoiceCharacter = QtWidgets.QMainWindow()
    ui = Ui_MainWindowChoiceCharacter()
    ui.setupUi(MainWindowChoiceCharacter)
    MainWindowChoiceCharacter.show()
    sys.exit(app.exec_())
