# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_room.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateRoomWindow(object):
    def setupUi(self, CreateRoomWindow):
        CreateRoomWindow.setObjectName("CreateRoomWindow")
        CreateRoomWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(CreateRoomWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(362, 256, 300, 255))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(5)
        self.frame.setObjectName("frame")
        self.labelBack = QtWidgets.QLabel(self.centralwidget)
        self.labelBack.setGeometry(QtCore.QRect(381, 272, 48, 48))
        self.labelBack.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBack.setObjectName("labelBack")
        self.labelNext = QtWidgets.QLabel(self.centralwidget)
        self.labelNext.setGeometry(QtCore.QRect(594, 272, 48, 48))
        self.labelNext.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNext.setObjectName("labelNext")
        self.labelCountOfPlayers = QtWidgets.QLabel(self.centralwidget)
        self.labelCountOfPlayers.setGeometry(QtCore.QRect(381, 379, 120, 21))
        self.labelCountOfPlayers.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCountOfPlayers.setObjectName("labelCountOfPlayers")
        self.buttonMinus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMinus.setGeometry(QtCore.QRect(515, 379, 29, 27))
        self.buttonMinus.setObjectName("buttonMinus")
        self.labelCounter = QtWidgets.QLabel(self.centralwidget)
        self.labelCounter.setGeometry(QtCore.QRect(568, 382, 20, 21))
        self.labelCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCounter.setObjectName("labelCounter")
        self.buttonPlus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPlus.setGeometry(QtCore.QRect(610, 379, 33, 27))
        self.buttonPlus.setObjectName("buttonPlus")
        CreateRoomWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateRoomWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        CreateRoomWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateRoomWindow)
        self.statusbar.setObjectName("statusbar")
        CreateRoomWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CreateRoomWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateRoomWindow)

    def retranslateUi(self, CreateRoomWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateRoomWindow.setWindowTitle(_translate("CreateRoomWindow", "Онлайн игра. Создание комнаты"))
        self.labelBack.setText(_translate("CreateRoomWindow", "back"))
        self.labelNext.setText(_translate("CreateRoomWindow", "next"))
        self.labelCountOfPlayers.setText(_translate("CreateRoomWindow", "Количество игроков"))
        self.buttonMinus.setText(_translate("CreateRoomWindow", "-"))
        self.labelCounter.setText(_translate("CreateRoomWindow", "4"))
        self.buttonPlus.setText(_translate("CreateRoomWindow", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateRoomWindow = QtWidgets.QMainWindow()
    ui = Ui_CreateRoomWindow()
    ui.setupUi(CreateRoomWindow)
    CreateRoomWindow.show()
    sys.exit(app.exec_())
