# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'get_random_role.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowRandomRole(object):
    def setupUi(self, MainWindowRandomRole):
        MainWindowRandomRole.setObjectName("MainWindowRandomRole")
        MainWindowRandomRole.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindowRandomRole)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(349, 189, 325, 390))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(5)
        self.frame.setObjectName("frame")
        self.labelBack = QtWidgets.QLabel(self.centralwidget)
        self.labelBack.setGeometry(QtCore.QRect(374, 215, 48, 48))
        self.labelBack.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBack.setObjectName("labelBack")
        self.labelNext = QtWidgets.QLabel(self.centralwidget)
        self.labelNext.setGeometry(QtCore.QRect(602, 215, 48, 48))
        self.labelNext.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNext.setObjectName("labelNext")
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelInfo.setGeometry(QtCore.QRect(486, 228, 68, 21))
        self.labelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInfo.setObjectName("labelInfo")
        self.labelRole = QtWidgets.QLabel(self.centralwidget)
        self.labelRole.setGeometry(QtCore.QRect(422, 279, 180, 260))
        self.labelRole.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRole.setObjectName("labelRole")
        MainWindowRandomRole.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowRandomRole)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindowRandomRole.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowRandomRole)
        self.statusbar.setObjectName("statusbar")
        MainWindowRandomRole.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowRandomRole)
        QtCore.QMetaObject.connectSlotsByName(MainWindowRandomRole)

    def retranslateUi(self, MainWindowRandomRole):
        _translate = QtCore.QCoreApplication.translate
        MainWindowRandomRole.setWindowTitle(_translate("MainWindowRandomRole", "Получена случайная роль"))
        self.labelBack.setText(_translate("MainWindowRandomRole", "<"))
        self.labelNext.setText(_translate("MainWindowRandomRole", ">"))
        self.labelInfo.setText(_translate("MainWindowRandomRole", "Ваша роль:"))
        self.labelRole.setText(_translate("MainWindowRandomRole", "Role"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowRandomRole = QtWidgets.QMainWindow()
    ui = Ui_MainWindowRandomRole()
    ui.setupUi(MainWindowRandomRole)
    MainWindowRandomRole.show()
    sys.exit(app.exec_())
