# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'online1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowOnline1(object):
    def setupUi(self, MainWindowOnline1):
        MainWindowOnline1.setObjectName("MainWindowOnline1")
        MainWindowOnline1.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindowOnline1)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(412, 299, 200, 170))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(5)
        self.frame.setObjectName("frame")
        self.buttonEnter = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEnter.setGeometry(QtCore.QRect(450, 330, 123, 27))
        self.buttonEnter.setObjectName("buttonEnter")
        self.buttonRegistration = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRegistration.setGeometry(QtCore.QRect(450, 370, 123, 27))
        self.buttonRegistration.setObjectName("buttonRegistration")
        self.buttonBack = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBack.setGeometry(QtCore.QRect(450, 410, 123, 27))
        self.buttonBack.setObjectName("buttonBack")
        MainWindowOnline1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowOnline1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindowOnline1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowOnline1)
        self.statusbar.setObjectName("statusbar")
        MainWindowOnline1.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowOnline1)
        QtCore.QMetaObject.connectSlotsByName(MainWindowOnline1)

    def retranslateUi(self, MainWindowOnline1):
        _translate = QtCore.QCoreApplication.translate
        MainWindowOnline1.setWindowTitle(_translate("MainWindowOnline1", "Онлайн игра. Окно 1"))
        self.buttonEnter.setText(_translate("MainWindowOnline1", "Вход"))
        self.buttonRegistration.setText(_translate("MainWindowOnline1", "Регистрация"))
        self.buttonBack.setText(_translate("MainWindowOnline1", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowOnline1 = QtWidgets.QMainWindow()
    ui = Ui_MainWindowOnline1()
    ui.setupUi(MainWindowOnline1)
    MainWindowOnline1.show()
    sys.exit(app.exec_())
