# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RulesWindow(object):
    def setupUi(self, RulesWindow):
        RulesWindow.setObjectName("RulesWindow")
        RulesWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(RulesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelBack = QtWidgets.QLabel(self.centralwidget)
        self.labelBack.setGeometry(QtCore.QRect(15, 15, 48, 48))
        self.labelBack.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBack.setObjectName("labelBack")
        self.labelBackPage = QtWidgets.QLabel(self.centralwidget)
        self.labelBackPage.setGeometry(QtCore.QRect(208, 359, 48, 48))
        self.labelBackPage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBackPage.setObjectName("labelBackPage")
        self.labelNextPage = QtWidgets.QLabel(self.centralwidget)
        self.labelNextPage.setGeometry(QtCore.QRect(768, 359, 48, 48))
        self.labelNextPage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNextPage.setObjectName("labelNextPage")
        self.labelRules = QtWidgets.QLabel(self.centralwidget)
        self.labelRules.setGeometry(QtCore.QRect(272, 63, 480, 640))
        self.labelRules.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRules.setObjectName("labelRules")
        RulesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RulesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        RulesWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RulesWindow)
        self.statusbar.setObjectName("statusbar")
        RulesWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RulesWindow)
        QtCore.QMetaObject.connectSlotsByName(RulesWindow)

    def retranslateUi(self, RulesWindow):
        _translate = QtCore.QCoreApplication.translate
        RulesWindow.setWindowTitle(_translate("RulesWindow", "Правила"))
        self.labelBack.setText(_translate("RulesWindow", "<"))
        self.labelBackPage.setText(_translate("RulesWindow", "<"))
        self.labelNextPage.setText(_translate("RulesWindow", ">"))
        self.labelRules.setText(_translate("RulesWindow", "Rules"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RulesWindow = QtWidgets.QMainWindow()
    ui = Ui_RulesWindow()
    ui.setupUi(RulesWindow)
    RulesWindow.show()
    sys.exit(app.exec_())
