# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'single1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowSingle1(object):
    def setupUi(self, MainWindowSingle1):
        MainWindowSingle1.setObjectName("MainWindowSingle1")
        MainWindowSingle1.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindowSingle1)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(362, 256, 300, 255))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(5)
        self.frame.setObjectName("frame")
        self.labelBack = QtWidgets.QLabel(self.centralwidget)
        self.labelBack.setGeometry(QtCore.QRect(381, 272, 48, 48))
        self.labelBack.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBack.setObjectName("labelBack")
        self.labelNext = QtWidgets.QLabel(self.centralwidget)
        self.labelNext.setGeometry(QtCore.QRect(594, 272, 48, 48))
        self.labelNext.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNext.setObjectName("labelNext")
        self.labelPlayers = QtWidgets.QLabel(self.centralwidget)
        self.labelPlayers.setGeometry(QtCore.QRect(381, 352, 120, 21))
        self.labelPlayers.setObjectName("labelPlayers")
        self.labelLevel = QtWidgets.QLabel(self.centralwidget)
        self.labelLevel.setGeometry(QtCore.QRect(381, 389, 120, 21))
        self.labelLevel.setObjectName("labelLevel")
        self.buttonPlayersMinus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPlayersMinus.setGeometry(QtCore.QRect(515, 352, 33, 27))
        self.buttonPlayersMinus.setObjectName("buttonPlayersMinus")
        self.buttonPlayersPlus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPlayersPlus.setGeometry(QtCore.QRect(610, 352, 33, 27))
        self.buttonPlayersPlus.setObjectName("buttonPlayersPlus")
        self.buttonLevelMinus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLevelMinus.setGeometry(QtCore.QRect(515, 389, 33, 27))
        self.buttonLevelMinus.setObjectName("buttonLevelMinus")
        self.buttonLevelPlus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLevelPlus.setGeometry(QtCore.QRect(610, 389, 33, 27))
        self.buttonLevelPlus.setObjectName("buttonLevelPlus")
        self.labelPlayersInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelPlayersInfo.setGeometry(QtCore.QRect(572, 355, 20, 21))
        self.labelPlayersInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPlayersInfo.setObjectName("labelPlayersInfo")
        self.labelLevelInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelLevelInfo.setGeometry(QtCore.QRect(560, 392, 43, 21))
        self.labelLevelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLevelInfo.setObjectName("labelLevelInfo")
        MainWindowSingle1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowSingle1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindowSingle1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowSingle1)
        self.statusbar.setObjectName("statusbar")
        MainWindowSingle1.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowSingle1)
        QtCore.QMetaObject.connectSlotsByName(MainWindowSingle1)

    def retranslateUi(self, MainWindowSingle1):
        _translate = QtCore.QCoreApplication.translate
        MainWindowSingle1.setWindowTitle(_translate("MainWindowSingle1", "Одиночная игра. Окно 1"))
        self.labelBack.setText(_translate("MainWindowSingle1", "<"))
        self.labelNext.setText(_translate("MainWindowSingle1", ">"))
        self.labelPlayers.setText(_translate("MainWindowSingle1", "Количество игроков"))
        self.labelLevel.setText(_translate("MainWindowSingle1", "Уровень сложности"))
        self.buttonPlayersMinus.setText(_translate("MainWindowSingle1", "-"))
        self.buttonPlayersPlus.setText(_translate("MainWindowSingle1", "+"))
        self.buttonLevelMinus.setText(_translate("MainWindowSingle1", "-"))
        self.buttonLevelPlus.setText(_translate("MainWindowSingle1", "+"))
        self.labelPlayersInfo.setText(_translate("MainWindowSingle1", "4"))
        self.labelLevelInfo.setText(_translate("MainWindowSingle1", "Лёгкий"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowSingle1 = QtWidgets.QMainWindow()
    ui = Ui_MainWindowSingle1()
    ui.setupUi(MainWindowSingle1)
    MainWindowSingle1.show()
    sys.exit(app.exec_())
